### ISSUE TITLE
Issue installation of Transmicron

### ISSUE THREAD

**Issue by Sanfranks** [gagneurlab/transmicron#1]
Hello,

I am trying to install transmicron in a conda environment, which is not resolvable.

The following error is generated but the requested versions collide / can't be installed:
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested _openmp_mutex 4.5**
  - nothing provides requested alsa-lib 1.2.3.2**
  - nothing provides requested binutils_linux-64 2.36**
  - nothing provides requested gcc_impl_linux-64 9.4.0**
  - nothing provides requested gcc_linux-64 9.4.0**
  - nothing provides requested gfortran_impl_linux-64 9.4.0**
  - nothing provides requested gfortran_linux-64 9.4.0**
  - nothing provides requested gxx_impl_linux-64 9.4.0**
  - nothing provides requested gxx_linux-64 9.4.0**
  - nothing provides requested keyutils 1.6.1**
  - nothing provides requested libgcc-devel_linux-64 9.4.0**
  - nothing provides requested libgcc-ng 11.2.0**
  - nothing provides requested libgfortran-ng 11.2.0**
  - nothing provides requested libgomp 11.2.0**
  - nothing provides requested libsanitizer 9.4.0**
  - nothing provides requested libstdcxx-devel_linux-64 9.4.0**
  - nothing provides requested libstdcxx-ng 11.2.0**
  - nothing provides requested libxkbcommon 1.0.3**
  - nothing provides requested patchelf 0.14.5**
  - package pango-1.48.10-h056538c_2 requires fontconfig >=2.13.1,<2.13.96.0a0, but none of the providers can be installed

How would you solve this and is an updated environment necessary?

Thank you for your help and best regards
Fran

**Comment by AtaJadidAhari** [comment]
Hi, I tried to recreate the environment from the current yaml file and it works on our servers (Linux OS) without any problems. Can you please let us know which operating system you are using? 
Also can you please try `conda search gcc_impl_linux-64==9.4`  to see if you can find the package separately?  
Also if you are using microconda or mamba, you could try again with conda. Sometimes packages are not maintained properly in mamba. You can also try to comment out all of the problematic packages from yaml file and see whether you can successfully create the environment.

please keep us updated, 

Best, Ata

**Comment by Sanfranks** [comment]
Hi Ata,

Thank you very much for your fast reply!
As suggested, I switched to conda and it now works for the dry run - seems to have been a compatibility issue.

Best regards
Francis
